import { z } from 'zod';
import { SortOrderSchema } from '../enums/SortOrder.schema';

import type { Prisma } from '../../../../generated/prisma';

const Schema: z.ZodType<Prisma.ReportCountOrderByAggregateInput> = z
  .object({
    id: z.lazy(() => SortOrderSchema).optional(),
    shipName: z.lazy(() => SortOrderSchema).optional(),
    imoNumber: z.lazy(() => SortOrderSchema).optional(),
    incidentDate: z.lazy(() => SortOrderSchema).optional(),
    reportedAt: z.lazy(() => SortOrderSchema).optional(),
    dpaName: z.lazy(() => SortOrderSchema).optional(),
    dpaPhone: z.lazy(() => SortOrderSchema).optional(),
    dpaMobile: z.lazy(() => SortOrderSchema).optional(),
    dpaEmail: z.lazy(() => SortOrderSchema).optional(),
    userId: z.lazy(() => SortOrderSchema).optional(),
    createdAt: z.lazy(() => SortOrderSchema).optional(),
    updatedAt: z.lazy(() => SortOrderSchema).optional(),
    mediaUrls: z.lazy(() => SortOrderSchema).optional(),
    flag: z.lazy(() => SortOrderSchema).optional(),
    shipType: z.lazy(() => SortOrderSchema).optional(),
    registrationType: z.lazy(() => SortOrderSchema).optional(),
    positionOfVessel: z.lazy(() => SortOrderSchema).optional(),
    locationOfVessel: z.lazy(() => SortOrderSchema).optional(),
    areaOfIncident: z.lazy(() => SortOrderSchema).optional(),
    yearBuilt: z.lazy(() => SortOrderSchema).optional(),
    deadweight: z.lazy(() => SortOrderSchema).optional(),
    gt: z.lazy(() => SortOrderSchema).optional(),
    maxDraft: z.lazy(() => SortOrderSchema).optional(),
    classificationSociety: z.lazy(() => SortOrderSchema).optional(),
    piClub: z.lazy(() => SortOrderSchema).optional(),
    hullMachineryUnderwriters: z.lazy(() => SortOrderSchema).optional(),
    totalCrewOnBoard: z.lazy(() => SortOrderSchema).optional(),
    conditionLoadedBallast: z.lazy(() => SortOrderSchema).optional(),
    severityOfIncident: z.lazy(() => SortOrderSchema).optional(),
    lastPortOfCall: z.lazy(() => SortOrderSchema).optional(),
    freeboard: z.lazy(() => SortOrderSchema).optional(),
    cargoTypeQty: z.lazy(() => SortOrderSchema).optional(),
    bunkers: z.lazy(() => SortOrderSchema).optional(),
    ownershipType: z.lazy(() => SortOrderSchema).optional(),
    techManagerName: z.lazy(() => SortOrderSchema).optional(),
    techManagerAddress: z.lazy(() => SortOrderSchema).optional(),
    techManagerPhone: z.lazy(() => SortOrderSchema).optional(),
    techManagerEmail: z.lazy(() => SortOrderSchema).optional(),
    rpsAgencyName: z.lazy(() => SortOrderSchema).optional(),
    rpsAgencyContactName: z.lazy(() => SortOrderSchema).optional(),
    rpsAgencyPhone: z.lazy(() => SortOrderSchema).optional(),
    rpsAgencyEmail: z.lazy(() => SortOrderSchema).optional(),
    localAgencyName: z.lazy(() => SortOrderSchema).optional(),
    localAgencyContactName: z.lazy(() => SortOrderSchema).optional(),
    localAgencyPhone: z.lazy(() => SortOrderSchema).optional(),
    localAgencyEmail: z.lazy(() => SortOrderSchema).optional(),
    incidentCategory: z.lazy(() => SortOrderSchema).optional(),
    incidentConsequences: z.lazy(() => SortOrderSchema).optional(),
    deaths: z.lazy(() => SortOrderSchema).optional(),
    injured: z.lazy(() => SortOrderSchema).optional(),
    deceasedDetails: z.lazy(() => SortOrderSchema).optional(),
    summaryIncident: z.lazy(() => SortOrderSchema).optional(),
    summaryAction: z.lazy(() => SortOrderSchema).optional(),
    lessonsLearnt: z.lazy(() => SortOrderSchema).optional(),
    sarRequired: z.lazy(() => SortOrderSchema).optional(),
    oilPollutionExtent: z.lazy(() => SortOrderSchema).optional(),
    weatherConditions: z.lazy(() => SortOrderSchema).optional(),
    tidalConditions: z.lazy(() => SortOrderSchema).optional(),
    oilSpilledVolume: z.lazy(() => SortOrderSchema).optional(),
  })
  .strict();

export const ReportCountOrderByAggregateInputObjectSchema = Schema;
