import { z } from 'zod';

import type { Prisma } from '../../../../generated/prisma';

const Schema: z.ZodType<Prisma.ReportMinAggregateInputType> = z
  .object({
    id: z.literal(true).optional(),
    shipName: z.literal(true).optional(),
    imoNumber: z.literal(true).optional(),
    incidentDate: z.literal(true).optional(),
    reportedAt: z.literal(true).optional(),
    dpaName: z.literal(true).optional(),
    dpaPhone: z.literal(true).optional(),
    dpaMobile: z.literal(true).optional(),
    dpaEmail: z.literal(true).optional(),
    userId: z.literal(true).optional(),
    createdAt: z.literal(true).optional(),
    updatedAt: z.literal(true).optional(),
    flag: z.literal(true).optional(),
    shipType: z.literal(true).optional(),
    registrationType: z.literal(true).optional(),
    positionOfVessel: z.literal(true).optional(),
    locationOfVessel: z.literal(true).optional(),
    areaOfIncident: z.literal(true).optional(),
    yearBuilt: z.literal(true).optional(),
    deadweight: z.literal(true).optional(),
    gt: z.literal(true).optional(),
    maxDraft: z.literal(true).optional(),
    classificationSociety: z.literal(true).optional(),
    piClub: z.literal(true).optional(),
    hullMachineryUnderwriters: z.literal(true).optional(),
    totalCrewOnBoard: z.literal(true).optional(),
    conditionLoadedBallast: z.literal(true).optional(),
    severityOfIncident: z.literal(true).optional(),
    lastPortOfCall: z.literal(true).optional(),
    freeboard: z.literal(true).optional(),
    cargoTypeQty: z.literal(true).optional(),
    bunkers: z.literal(true).optional(),
    ownershipType: z.literal(true).optional(),
    techManagerName: z.literal(true).optional(),
    techManagerAddress: z.literal(true).optional(),
    techManagerPhone: z.literal(true).optional(),
    techManagerEmail: z.literal(true).optional(),
    rpsAgencyName: z.literal(true).optional(),
    rpsAgencyContactName: z.literal(true).optional(),
    rpsAgencyPhone: z.literal(true).optional(),
    rpsAgencyEmail: z.literal(true).optional(),
    localAgencyName: z.literal(true).optional(),
    localAgencyContactName: z.literal(true).optional(),
    localAgencyPhone: z.literal(true).optional(),
    localAgencyEmail: z.literal(true).optional(),
    incidentCategory: z.literal(true).optional(),
    incidentConsequences: z.literal(true).optional(),
    deaths: z.literal(true).optional(),
    injured: z.literal(true).optional(),
    deceasedDetails: z.literal(true).optional(),
    summaryIncident: z.literal(true).optional(),
    summaryAction: z.literal(true).optional(),
    lessonsLearnt: z.literal(true).optional(),
    sarRequired: z.literal(true).optional(),
    oilPollutionExtent: z.literal(true).optional(),
    weatherConditions: z.literal(true).optional(),
    tidalConditions: z.literal(true).optional(),
    oilSpilledVolume: z.literal(true).optional(),
  })
  .strict();

export const ReportMinAggregateInputObjectSchema = Schema;
